AppBundle\Entity\Posts:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PostsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        description:
            type: string
            length: '255'
        img:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
